# code-server
RUN ARCH="$(dpkg --print-architecture)" && \
    curl -s https://api.github.com/repos/cdr/code-server/releases/latest  | grep "browser_download_url" | grep -Eo "https://[^\"]*$ARCH.deb" | xargs wget -O /tmp/code-server.deb && \
    dpkg -i /tmp/code-server.deb && rm /tmp/code-server.deb
