name: Docker Image CI

on:
  workflow_dispatch: #allows you to trigger manually

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: DockerHub Login
      run: |
        echo PASSWORD|dockerlogin−uUSERNAME --password-stdin
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: bash build_all.sh
