RUN rustup component add rust-src

RUN apt-get update && \
    apt-get install -y cmake build-essential

# Install jupyter
RUN cargo install evcxr_jupyter
RUN evcxr_jupyter --install

ENV NOTEBOOK_CONFIG="/root/.jupyter/jupyter_notebook_config.py"
RUN mkdir -p /root/.jupyter && \
    echo "c.ServerApp.ip = '0.0.0.0'" >> ${NOTEBOOK_CONFIG} && \
    echo "c.ServerApp.allow_root = True" >> ${NOTEBOOK_CONFIG} && \
    echo "c.NotebookApp.open_browser = False" >> ${NOTEBOOK_CONFIG}
