ENV SHELL /bin/bash
EXPOSE 8888
WORKDIR /data
CMD ["jupyter", "notebook"]
# CMD [ "conda activate base && jupyter notebook --allow-root --no-browser --ip=0.0.0.0 --port=8080 --NotebookApp.token='' --NotebookApp.password=''" ]
